### ISSUE TITLE
I want to join your organization.

### ISSUE THREAD

**Issue by Kushal997-das** [risk-first/automation#1]

**Comment by robmoffat** [comment]
Hi Kushal - star the website repo and you should get an organisational invite

cheers,
Rob

**Comment by Kushal997-das** [comment]
> Hi Kushal - star the website repo and you should get an organisational invite
> 
> cheers,
> Rob

[This repo ](https://github.com/risk-first/automation/) Right?

**Comment by robmoffat** [comment]
I see you’re in!

**Comment by Kushal997-das** [comment]
Thanks :)
